print()

str = 'ViNiCiuS aLBuQueRQue NóBReGa'
print(str.capitalize())
print(str.casefold())
print(str.center(50))
print(str.count('A'))
print(str.encode())
print(str.endswith('A'))
print(str.find('i'))
print(str.format())
print(str.format_map('ó'))
print(str.index('e'))
print(str.isalnum())
print(str.isalpha())
print(str.isascii())
print(str.isdecimal())
print(str.isdigit())
print(str.isidentifier())
print(str.islower())
print(str.isnumeric())
print(str.isprintable())
print(str.isspace())
print(str.istitle())
print(str.isupper())
print(str.join('-'))
print(str.ljust(8,'V'))
print(str.lower())
print(str.lstrip())
print(str.maketrans('a' , 'b' , 'c' ))
print(str.partition('R'))
print(str.removeprefix('Vinícius'))
print(str.removesuffix('Nóbrega'))
print(str.replace(' ', '_'))
print(str.rfind('i'))
print(str.rindex('i'))
print(str.rjust(8,'V'))
print(str.rpartition(' '))
print(str.rsplit())
print(str.rstrip())
print(str.swapcase())
print(str.title())
print(str.translate('a'))
print(str.upper())
print(str.zfill(10))

print()