print()

frase = 'Curso em Vídeo Python'
print('\n>> Caractere na posição 9 é:\n{}' .format(frase[9]))
print('\n>> Letra na posição 10 é:\n{}' .format(frase[9]))
print('\n>> Caracteres nas posições 9 a 12 são:\n{}' .format(frase[9: 13]))
print('\n>> Letras nas posições 10 a 13 são:\n{}' .format(frase[9: 13]))
print('\n>> Caracteres nas posições 9 a 20 são:\n{}' .format(frase[9: 21]))
print('\n/{:=^97}\\' .format(' OBSERVAÇÃO '))
print('{} Ao pedir caracteres acima do tamanho máximo da variável só será mostrado o tamanho da variável. {}' .format('|','|'))
print('\{:=^97}/' .format(''))
print('{}' .format(frase[9: 30]))
print('\n>> Mostrar letras da posição 9 até 21 mostrando a cada 2 espaços:\n{}' .format(frase[9:21:2]))
print('\n>> Mostrar letras até a posição determinada:\n{}' .format(frase[:5]))
print('\n>> Este exemplo mostra igual ao anterior, mas com uma formatação completa:\n{}' .format(frase[0:5]))
print('\n>> Para mostrar todos os caracteres a partir de uma determinada posição:\n{}' .format(frase[15:]))
print('\n>> Este faz o mesmo que o anterior, mas com uma formatação completa:\n{}' .format(frase[15:21]))
print('\n>> Mostra letras começanco na posição 9 até o final (omitido) a cada 3 espaços:\n{}' .format(frase[9::3]))
print('\n>> A função "len" é utilizada para determinar o tamanho de uma variável string:\n{} posições' .format(len(frase)))
print('\n>> Contador de um determinado caractere:\nO caractere {} aparece {} vezes na frase: {}' .format('\'o\'', frase.count('o'), frase))
print('O caractere {} aparece {} vezes da posição 0 a 12 (13-1) na frase: {}' .format('\'o\'', frase.count('o',0,13), frase))
print('\n>> Em qual posição começa a sequencia \'deo\' na frase ({})?\nResposta: {}' .format(frase, frase.find('deo')))
print('\n>> Em qual posição começa a sequencia \'Android\' na frase ({})?\nResposta: {}' .format(frase, frase.find('Android')))
print('\n>> Mostra Verdadeiro ou Falso caso a sequencia \'{}\' apareca na frase.\n' .format(frase[0:5]) ,'Curso' in frase)
frase = frase.replace('Python', 'Android')
print('\n>> Em qual posição começa a sequencia \'Android\' na frase ({})?\nResposta: {}' .format(frase, frase.find('Android')))
frase = frase.replace('Android', 'Python')
print('\n>> Mostra a frase toda em maiúscula:\n{}' .format(frase.upper()))
print('\n>> Mostra a frase toda em minúscula:\n{}' .format(frase.lower()))
print('\n>> Mostra a frase com a primeira letra Maiúscula:\n{}' .format(frase.capitalize()))
print('\n>> Mostra a frase com a primeira letra de cada palavras em Maiúscula:\n{}' .format(frase.title()))
frase = '   ' + frase + '   '
print('\n>> Mostra 4 funções atreladas a variável do tipo string:')
print('{}{}' .format(frase, '=> Frase com espaços.'))
print('{}=>{}<={}' .format(frase, frase.strip(), ' Frase sem os espaços esquerdo e direito.'))
print('{}=>{}<={}' .format(frase, frase.rstrip(), ' Frase sem os espaços da direita.'))
print('{}=>{}<={}' .format(frase, frase.lstrip(), ' Frase sem os espaços da esquerda.'))
frase = frase.split()
print('{} =>{}' .format(frase, ' Frase transformada em lista por palavra.'))
print('{} =>{}<={}' .format(frase, '-'.join(frase), ' Frase transformada em cadeia completa. Espaços são substituidos por \'-\''))

print()