print()
print('As variáveis são espaços de memória que podem ser atribuídos valores a elas.')
print('Esses valores podem ter Tipos diferentes.')
print()
print('Inteiro:  Chamado de "int"')
print('Decimal:  Chamado de "float" ou ponto flutuante')
print('Booleano: Chamado de "bool" ou "Verdadeiro ou Falso"')
print('Textual:  Chamado de "str" ou string (cadeia de caracteres)')
print()
print('EXEMPLOS:')
print()
print('int = {1, 3, 5, 98823} etc')
print('float = {1.3, 3.1, 5.0, 15,23} ')
print('bool = {True, False}')
print('str = {"Vinícius", "39", "M", "V336", "+"}')
print()